"use client";

import React, { useState } from "react";
import { BarChart2, TrendingUp, DollarSign, Users, Activity, Sparkles, ArrowUpRight, ArrowDownRight, Layers } from "lucide-react";

export function ChartsSection() {
  const [timeframe, setTimeframe] = useState("30D");

  const revenueData = [
    { day: "Day 1", value: 0, label: "$0.0k" },
    { day: "Day 5", value: 0, label: "$0.0k" },
    { day: "Day 10", value: 0, label: "$0.0k" },
    { day: "Day 15", value: 0, label: "$0.0k" },
    { day: "Day 20", value: 0, label: "$0.0k" },
    { day: "Day 25", value: 0, label: "$0.0k" },
    { day: "Today", value: 0, label: "$0.0k" },
  ];

  const expenseBreakdown = [
    { category: "Pending Data Connection", amount: "$0", percentage: 100, color: "bg-neutral-200" },
  ];

  return (
    <section className="space-y-6">
      {/* Top Header & Controls */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-6 rounded-2xl bg-white border border-neutral-200 shadow-sm relative overflow-hidden">
        <div className="flex items-center gap-3">
          <div className="p-2.5 rounded-xl bg-black text-white shadow-xs">
            <BarChart2 className="h-4 w-4" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 className="text-base font-bold text-black tracking-tight">
                Executive Financial & Operational Analytics
              </h3>
              <span className="px-1.5 py-0.2 rounded bg-neutral-100 text-neutral-800 border border-neutral-300 text-[10px] font-mono font-bold uppercase">
                REAL-TIME TELEMETRY
              </span>
            </div>
            <p className="text-xs text-neutral-500 mt-0.5">
              Continuous multi-source data synthesis generated by Finance and Analytics agents
            </p>
          </div>
        </div>

        {/* Timeframe Selector */}
        <div className="flex items-center gap-1 bg-neutral-100 p-1 rounded-xl border border-neutral-200 self-start sm:self-auto">
          {["7D", "30D", "90D", "1Y", "ALL"].map((tf) => (
            <button
              key={tf}
              onClick={() => setTimeframe(tf)}
              className={`px-3 py-1 rounded-lg text-xs font-mono transition-all cursor-pointer ${
                timeframe === tf
                  ? "bg-black text-white font-bold shadow-xs"
                  : "text-neutral-600 hover:text-black hover:bg-neutral-200/60"
              }`}
            >
              {tf}
            </button>
          ))}
        </div>
      </div>

      {/* Two Column Grid: Revenue Area Chart & Expense Distribution */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left 2 Cols: Revenue Trajectory Area Chart */}
        <div className="lg:col-span-2 p-6 rounded-2xl bg-white border border-neutral-200 shadow-sm flex flex-col justify-between relative overflow-hidden group">
          <div>
            <div className="flex items-center justify-between mb-2">
              <div>
                <span className="text-[11px] font-mono text-neutral-500 uppercase tracking-wider font-semibold">
                  Revenue Growth Trajectory (ARR Velocity)
                </span>
                <div className="flex items-baseline gap-3 mt-1">
                  <span className="text-3xl font-extrabold text-black font-mono tracking-tight">$0</span>
                  <span className="text-xs font-mono font-bold text-neutral-400 flex items-center gap-0.5 bg-neutral-100 px-2 py-0.5 rounded border border-neutral-300">
                    <span>—</span>
                  </span>
                </div>
              </div>

              <div className="text-right hidden sm:block">
                <span className="text-[10px] font-mono text-neutral-400 uppercase">Target Series A ARR</span>
                <div className="text-sm font-mono font-bold text-neutral-400 mt-0.5">Not set</div>
              </div>
            </div>
            <p className="text-xs text-neutral-500 font-normal">
              Reconciled across Stripe billing and enterprise ACH wire transfers in real time.
            </p>
          </div>

          {/* Pure SVG Minimalist Area Chart */}
          <div className="mt-8 pt-4 h-56 w-full relative flex items-end">
            <svg className="w-full h-full overflow-visible" viewBox="0 0 600 200" preserveAspectRatio="none">
              <defs>
                <linearGradient id="revenueGradient" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="0%" stopColor="#000000" stopOpacity="0.15" />
                  <stop offset="100%" stopColor="#000000" stopOpacity="0.0" />
                </linearGradient>
              </defs>

              {/* Grid lines */}
              <line x1="0" y1="50" x2="600" y2="50" stroke="#f5f5f5" strokeWidth="1" strokeDasharray="4 4" />
              <line x1="0" y1="100" x2="600" y2="100" stroke="#f5f5f5" strokeWidth="1" strokeDasharray="4 4" />
              <line x1="0" y1="150" x2="600" y2="150" stroke="#f5f5f5" strokeWidth="1" strokeDasharray="4 4" />

              {/* Area fill */}
              <path
                d="M 0 200 L 100 200 L 200 200 L 300 200 L 400 200 L 500 200 L 600 200 L 600 200 L 0 200 Z"
                fill="url(#revenueGradient)"
              />

              {/* Stroke path */}
              <path
                d="M 0 200 L 100 200 L 200 200 L 300 200 L 400 200 L 500 200 L 600 200"
                fill="none"
                stroke="#000000"
                strokeWidth="2.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              />

              {/* Data points & tooltips */}
              {[
                { x: 0, y: 200, val: "$0.0k" },
                { x: 100, y: 200, val: "$0.0k" },
                { x: 200, y: 200, val: "$0.0k" },
                { x: 300, y: 200, val: "$0.0k" },
                { x: 400, y: 200, val: "$0.0k" },
                { x: 500, y: 200, val: "$0.0k" },
                { x: 600, y: 200, val: "$0.0k (Today)" },
              ].map((pt, i) => (
                <g key={i} className="group/pt">
                  <circle
                    cx={pt.x}
                    cy={pt.y}
                    r={i === 6 ? "5" : "3.5"}
                    className={i === 6 ? "fill-black stroke-white stroke-2" : "fill-white stroke-black stroke-2"}
                  />
                  <text
                    x={pt.x === 600 ? pt.x - 35 : pt.x}
                    y={pt.y - 12}
                    textAnchor="middle"
                    className="text-[10px] font-mono fill-neutral-700 font-bold opacity-0 group-hover/pt:opacity-100 transition-opacity"
                  >
                    {pt.val}
                  </text>
                </g>
              ))}
            </svg>
          </div>

          {/* X Axis Labels */}
          <div className="flex items-center justify-between text-[11px] font-mono text-neutral-400 mt-3 pt-2 border-t border-neutral-100">
            {revenueData.map((d, i) => (
              <span key={i} className={i === 6 ? "text-black font-bold" : ""}>
                {d.day}
              </span>
            ))}
          </div>
        </div>

        {/* Right Col: Expense Distribution & Burn Rate Breakdown */}
        <div className="p-6 rounded-2xl bg-white border border-neutral-200 shadow-sm flex flex-col justify-between relative overflow-hidden">
          <div>
            <div className="flex items-center justify-between mb-2">
              <span className="text-[11px] font-mono text-neutral-500 uppercase tracking-wider font-semibold">
                Monthly Burn Breakdown
              </span>
              <span className="text-xs font-mono font-bold text-neutral-400">$0 / mo</span>
            </div>
            <h4 className="text-base font-bold text-black tracking-tight">
              Operating Spend Allocation
            </h4>
            <p className="text-xs text-neutral-500 mt-1">
              Connect finance integrations to begin analyzing your runway and spend.
            </p>
          </div>

          {/* Stacked Progress Bar */}
          <div className="my-6">
            <div className="w-full h-3 rounded-full bg-neutral-100 overflow-hidden flex gap-0.5 p-0.5 border border-neutral-200">
              {expenseBreakdown.map((ex, idx) => (
                <div
                  key={idx}
                  style={{ width: `${ex.percentage}%` }}
                  className={`h-full rounded-xs ${ex.color} transition-all duration-500`}
                  title={`${ex.category}: ${ex.amount}`}
                />
              ))}
            </div>
          </div>

          {/* Category List */}
          <div className="space-y-3">
            {expenseBreakdown.map((ex, idx) => (
              <div
                key={idx}
                className="p-3 rounded-xl bg-neutral-50 hover:bg-neutral-100 border border-neutral-200 flex items-center justify-between text-xs transition-colors"
              >
                <div className="flex items-center gap-2.5 min-w-0">
                  <div className={`h-3 w-3 rounded-xs shrink-0 ${ex.color}`} />
                  <span className="text-neutral-800 font-medium truncate">{ex.category}</span>
                </div>
                <div className="text-right shrink-0 font-mono">
                  <div className="font-bold text-black">{ex.amount}</div>
                  <div className="text-[10px] text-neutral-400">{ex.percentage}%</div>
                </div>
              </div>
            ))}
          </div>

          <div className="mt-6 pt-3 border-t border-neutral-100 flex items-center justify-between text-[11px] font-mono text-neutral-500">
            <span>Next payroll sync: in 4 days</span>
            <span className="text-black font-semibold flex items-center gap-1 cursor-pointer hover:underline">
              <span>View QuickBooks Ledger</span>
              <ArrowUpRight className="h-3 w-3" />
            </span>
          </div>
        </div>
      </div>
    </section>
  );
}
